name: custom-nodejs
services:
  my-app:
    build:
      context: ./images/nodejs/
    volumes:
      - ./volumes/my-app:/home/node/my-app:Z
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
      - "9229:9229"
    command: [ "node", "--inspect-brk=0.0.0.0" , "." ]

